config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :documents, only: [:new, :create, :index]
  root to: 'documents#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many_attached :documents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :authenticate_user!

  def index
    @documents = current_user.documents

    render new_document_path
  end

  def new
    @document = current_user.documents.build
  end

  def show
    @document = current_user.documents.find(params[:id])
    @parsed_data = parse_xml(@document.download)
  end

  def create
    if params[:document].present?
      params[:document].each do |doc|
        attached_file = current_user.documents.attach(doc).first
        ProcessXmlJob.perform_later(attached_file.signed_id) if attached_file.present?
      end
      redirect_to documents_path, notice: 'Documentos enviados com sucesso!'
    else
      render :new
    end
  end

  private

  def parse_xml(xml_data)
    doc = Nokogiri::XML(xml_data)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/index.html.erb
<h1>Meus Documentos</h1>
<ul>
  <% @documents.each do |document| %>
    <li><%= link_to document.filename.to_s, url_for(document) %></li>
  <% end %>
</ul>

app/views/documents/new.html.erb
<h1>Enviar Documentos</h1>
<%= form_with url: documents_path, local: true, multipart: true do %>
  <%= file_field_tag "document[]", multiple: true %>
  <%= submit_tag "Enviar" %>
<% end %>

app/views/documents/show.html.erb
<h1>Relatório do Documento</h1>

<%= form_with url: document_path(@document), method: :get, local: true do %>
  <%= text_field_tag :nNF, params[:nNF], placeholder: "Número da NF" %>
  <%= submit_tag "Filtrar" %>
<% end %>

<% @parsed_data.each do |data| %>
  <% if params[:nNF].blank? || data[:nNF] == params[:nNF] %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Files Processing" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>